// Generate all 67 styles data
const styles = [
  // General Styles (1-49)
  { id: 1, name: 'Minimalism & Swiss Style', category: 'general', desc: '极简主义与瑞士风格 - 企业应用、仪表板、文档', bg: '#ffffff', text: '#212529' },
  { id: 2, name: 'Neumorphism', category: 'general', desc: '新拟态 - 健康/养生应用、冥想平台', bg: '#e0e5ec', text: '#2d3748' },
  { id: 3, name: 'Glassmorphism', category: 'general', desc: '玻璃拟态 - 现代 SaaS、金融仪表板', bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', text: '#ffffff' },
  { id: 4, name: 'Brutalism', category: 'general', desc: '粗野主义 - 设计作品集、艺术项目', bg: '#ff6b6b', text: '#000000' },
  { id: 5, name: '3D & Hyperrealism', category: 'general', desc: '3D 与超写实 - 游戏、产品展示、沉浸式体验', bg: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)', text: '#2d3748' },
  { id: 6, name: 'Vibrant & Block-based', category: 'general', desc: '鲜艳色块 - 初创公司、创意机构、游戏', bg: 'linear-gradient(135deg, #ff6b6b 0%, #feca57 50%, #48dbfb 100%)', text: '#2d3436' },
  { id: 7, name: 'Dark Mode (OLED)', category: 'general', desc: '深色模式 - 夜间应用、编程平台', bg: '#0a0a0f', text: '#e4e4e7' },
  { id: 8, name: 'Accessible & Ethical', category: 'general', desc: '无障碍与伦理设计 - 政府、医疗、教育', bg: '#ffffff', text: '#000000' },
  { id: 9, name: 'Claymorphism', category: 'general', desc: '粘土拟态 - 教育应用、儿童应用、SaaS', bg: '#f0f3f8', text: '#2d3748' },
  { id: 10, name: 'Aurora UI', category: 'general', desc: '极光 UI - 现代 SaaS、创意机构', bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)', text: '#ffffff' },
  { id: 11, name: 'Retro-Futurism', category: 'general', desc: '复古未来主义 - 游戏、娱乐、音乐平台', bg: '#0c0c1d', text: '#00ffff' },
  { id: 12, name: 'Flat Design', category: 'general', desc: '扁平设计 - Web 应用、移动应用、初创 MVP', bg: '#ecf0f1', text: '#2c3e50' },
  { id: 13, name: 'Skeuomorphism', category: 'general', desc: '拟物化 - 遗留应用、游戏、高端产品', bg: 'linear-gradient(135deg, #e8e8e8 0%, #d0d0d0 100%)', text: '#333333' },
  { id: 14, name: 'Liquid Glass', category: 'general', desc: '液态玻璃 - 高端 SaaS、电商', bg: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)', text: '#ffffff' },
  { id: 15, name: 'Motion-Driven', category: 'general', desc: '动效驱动 - 作品集、故事平台', bg: '#0f0f23', text: '#ffffff' },
  { id: 16, name: 'Micro-interactions', category: 'general', desc: '微交互 - 移动应用、触屏 UI', bg: '#f7fafc', text: '#2d3748' },
  { id: 17, name: 'Inclusive Design', category: 'general', desc: '包容性设计 - 公共服务、教育、医疗', bg: '#ffffff', text: '#1a202c' },
  { id: 18, name: 'Zero Interface', category: 'general', desc: '零界面 - 语音助手、AI 平台', bg: '#000000', text: '#00ff00' },
  { id: 19, name: 'Soft UI Evolution', category: 'general', desc: '软 UI 进化 - 现代企业应用、SaaS', bg: '#f8f9fa', text: '#495057' },
  { id: 20, name: 'Neubrutalism', category: 'general', desc: '新粗野主义 - Z 世代品牌、初创公司', bg: '#ffe156', text: '#000000' },
  { id: 21, name: 'Bento Box Grid', category: 'general', desc: '便当盒网格 - 仪表板、产品页、作品集', bg: '#f5f5f5', text: '#1a1a1a' },
  { id: 22, name: 'Y2K Aesthetic', category: 'general', desc: '千禧年美学 - 时尚品牌、音乐、Z 世代', bg: 'linear-gradient(135deg, #ff00ff 0%, #00ffff 100%)', text: '#000000' },
  { id: 23, name: 'Cyberpunk UI', category: 'general', desc: '赛博朋克 - 游戏、科技产品、加密应用', bg: '#0a0a0f', text: '#00ffff' },
  { id: 24, name: 'Organic Biophilic', category: 'general', desc: '有机亲生物 - 养生应用、可持续品牌', bg: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)', text: '#2d3748' },
  { id: 25, name: 'AI-Native UI', category: 'general', desc: 'AI 原生界面 - AI 产品、聊天机器人、助手', bg: '#0f0f1a', text: '#ffffff' },
  { id: 26, name: 'Memphis Design', category: 'general', desc: '孟菲斯设计 - 创意机构、音乐、年轻品牌', bg: '#ffffff', text: '#2d3436' },
  { id: 27, name: 'Vaporwave', category: 'general', desc: '蒸汽波 - 音乐平台、游戏、作品集', bg: '#2d1b4e', text: '#00ffff' },
  { id: 28, name: 'Dimensional Layering', category: 'general', desc: '维度分层 - 仪表板、卡片布局、模态框', bg: '#f7fafc', text: '#2d3748' },
  { id: 29, name: 'Exaggerated Minimalism', category: 'general', desc: '夸张极简 - 时尚、建筑、作品集', bg: '#ffffff', text: '#000000' },
  { id: 30, name: 'Kinetic Typography', category: 'general', desc: '动态排版 - 首屏区域、营销网站', bg: '#0a0a0f', text: '#ffffff' },
  { id: 31, name: 'Parallax Storytelling', category: 'general', desc: '视差叙事 - 品牌故事、产品发布', bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', text: '#ffffff' },
  { id: 32, name: 'Swiss Modernism 2.0', category: 'general', desc: '瑞士现代主义 2.0 - 企业网站、建筑、编辑', bg: '#ffffff', text: '#000000' },
  { id: 33, name: 'HUD / Sci-Fi FUI', category: 'general', desc: 'HUD 科幻界面 - 科幻游戏、太空科技、网络安全', bg: '#001100', text: '#00ff00' },
  { id: 34, name: 'Pixel Art', category: 'general', desc: '像素艺术 - 独立游戏、复古工具、创意', bg: '#2d2d2d', text: '#ffffff' },
  { id: 35, name: 'Bento Grids', category: 'general', desc: '便当网格 - 产品功能、仪表板、个人', bg: '#f5f5f5', text: '#1a1a1a' },
  { id: 36, name: 'Spatial UI (VisionOS)', category: 'general', desc: '空间 UI - 空间计算应用、VR/AR', bg: '#000000', text: '#ffffff' },
  { id: 37, name: 'E-Ink / Paper', category: 'general', desc: '电子墨水/纸张 - 阅读应用、数字报纸', bg: '#f5f5dc', text: '#333333' },
  { id: 38, name: 'Gen Z Chaos / Maximalism', category: 'general', desc: 'Z 世代混乱/极繁主义 - Z 世代生活方式、音乐艺术家', bg: 'linear-gradient(135deg, #ff6b6b 0%, #feca57 25%, #48dbfb 50%, #ff9ff3 75%, #54a0ff 100%)', text: '#000000' },
  { id: 39, name: 'Biomimetic / Organic 2.0', category: 'general', desc: '仿生/有机 2.0 - 可持续科技、生物科技、健康', bg: 'linear-gradient(135deg, #a8e6cf 0%, #dcedc1 100%)', text: '#2d3748' },
  { id: 40, name: 'Anti-Polish / Raw Aesthetic', category: 'general', desc: '反抛光/原始美学 - 创意作品集、艺术家网站', bg: '#f0f0f0', text: '#000000' },
  { id: 41, name: 'Tactile Digital / Deformable UI', category: 'general', desc: '触觉数字/可变形 UI - 现代移动应用、趣味品牌', bg: '#f5f5f5', text: '#2d3748' },
  { id: 42, name: 'Nature Distilled', category: 'general', desc: '自然提炼 - 养生品牌、可持续产品', bg: 'linear-gradient(135deg, #d4fc79 0%, #96e6a1 100%)', text: '#2d3748' },
  { id: 43, name: 'Interactive Cursor Design', category: 'general', desc: '交互光标设计 - 创意作品集、交互式', bg: '#0a0a0f', text: '#ffffff' },
  { id: 44, name: 'Voice-First Multimodal', category: 'general', desc: '语音优先多模态 - 语音助手、无障碍应用', bg: '#1a1a2e', text: '#ffffff' },
  { id: 45, name: '3D Product Preview', category: 'general', desc: '3D 产品预览 - 电商、家具、时尚', bg: '#f5f5f5', text: '#2d3748' },
  { id: 46, name: 'Gradient Mesh / Aurora Evolved', category: 'general', desc: '渐变网格/极光进化 - 首屏区域、背景、创意', bg: 'linear-gradient(135deg, #ff00cc 0%, #333399 50%, #00ccff 100%)', text: '#ffffff' },
  { id: 47, name: 'Editorial Grid / Magazine', category: 'general', desc: '编辑网格/杂志 - 新闻网站、博客、杂志', bg: '#fafafa', text: '#1a1a1a' },
  { id: 48, name: 'Chromatic Aberration / RGB Split', category: 'general', desc: '色差/RGB 分离 - 音乐平台、游戏、科技', bg: '#0a0a0f', text: '#ffffff' },
  { id: 49, name: 'Vintage Analog / Retro Film', category: 'general', desc: '复古模拟/胶片 - 摄影、音乐/黑胶品牌', bg: '#f5f5dc', text: '#4a3728' },
  
  // Landing Page Styles (50-57)
  { id: 50, name: 'Hero-Centric Design', category: 'landing', desc: '首屏聚焦 - 具有强烈视觉识别度的产品', bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', text: '#ffffff' },
  { id: 51, name: 'Conversion-Optimized', category: 'landing', desc: '转化优化 - 线索生成、销售页面', bg: '#ffffff', text: '#2d3748' },
  { id: 52, name: 'Feature-Rich Showcase', category: 'landing', desc: '功能丰富展示 - SaaS、复杂产品', bg: '#f7fafc', text: '#2d3748' },
  { id: 53, name: 'Minimal & Direct', category: 'landing', desc: '极简直接 - 简单产品、应用', bg: '#ffffff', text: '#1a1a1a' },
  { id: 54, name: 'Social Proof-Focused', category: 'landing', desc: '社交证明导向 - 服务、B2C 产品', bg: '#f8f9fa', text: '#2d3748' },
  { id: 55, name: 'Interactive Product Demo', category: 'landing', desc: '交互式产品演示 - 软件、工具', bg: '#0a0a0f', text: '#ffffff' },
  { id: 56, name: 'Trust & Authority', category: 'landing', desc: '信任与权威 - B2B、企业、咨询', bg: '#ffffff', text: '#2d3748' },
  { id: 57, name: 'Storytelling-Driven', category: 'landing', desc: '叙事驱动 - 品牌、机构、非营利组织', bg: '#f7fafc', text: '#2d3748' },
  
  // Dashboard Styles (58-67)
  { id: 58, name: 'Data-Dense Dashboard', category: 'dashboard', desc: '高密度数据仪表板 - 复杂数据分析', bg: '#f7fafc